# Copyright 2013, Dell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "file:///home/crowbar/cb2/gemsite"
# source "file:///tmp/crowbar-dev-test/gemsite"
# source "file:///tftpboot/gemsite"
# source 'https://rubygems.org'

gem 'rails', '~> 3.2.13'

gem 'pg'
gem 'haml'
gem 'sass-rails',   '~> 3.2.3'
gem 'simple-navigation'
gem 'syslogger'
gem 'kwalify'
gem 'bluecloth', '>= 2.0.0'
gem 'puma'
#gem 'amqp'
gem 'xml-simple'
gem 'daemons'
gem 'active_scaffold'
gem 'devise', "~>3.0.0"
gem 'rails_config'
gem 'delayed_job'
gem 'delayed_job_active_record'
#gem 'rails-settings'

gem 'jquery-rails'

group :development, :test do
  gem "rails-erd"
  gem 'simplecov', :platforms => [:ruby_19,:ruby_20]
  gem 'coveralls', :platforms => [:ruby_19,:ruby_20]
  gem "factory_girl", "<3.0"
  gem "factory_girl_rails", "< 3.0"
  gem 'rspec-rails'
  gem "email_spec", ">= 1.2.1"
  gem "database_cleaner", ">= 0.7.2"
  gem "launchy", ">= 2.1.0"
end


# to use digest auth in cli unit tests
gem 'net-http-digest_auth'

# Install gems from each barclamp.  The crowbar_path variable is
# needed by Gemfile.d/*.gemfile so that they can determine the correct
# path at run-time rather than having to hard-code a path at
# install-time which may be different and therefore incorrect.
#crowbar_path = File.dirname(__FILE__)-
#Dir.glob(File.join(crowbar_path, 'Gemfile.d', '*.gemfile')) do |gemfile|
#    eval(IO.read(gemfile), binding)
#end
